title: sudo
description: "Very minimal theme for Jekyll aimed at personal blogging"
url: "http://alumbreras.github.io"  # the base hostname & protocol for your site
baseurl: "/maldekstrakolono" # the subpath of your site, e.g. /blog
twitter_username: unocerotres
github_username:  oneohthree
language: en_US
paginate: 10
paginate_path: "/page/:num/"
permalink: none
markdown: kramdown
