# General Jekyll Config
highlighter: pygments
url: "http://alumbreras.github.io/maldekstrakolono"  # the base hostname & protocol for your site
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
