encoding: utf-8

# Build settings
markdown: kramdown
highlighter: rouge

timezone: Europe/Berlin
baseurl: "https://maldekstrakolono.net" # the subpath of your site, e.g. /blog
#url: "http://alumbreras.github.io"  # the base hostname & protocol for your site
url: "https://maldekstrakolono.net"  # the base hostname & protocol for your site

exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']



header-img: images/maldekstra_banner_cut.png

