encoding: utf-8

# Build settings
markdown: kramdown
highlighter: rouge

timezone: Europe/Berlin
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maldekstrakolono.net"  # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title.html

exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']


gems:
  - jekyll-redirect-from
  
header-img: images/maldekstra_banner_cut.png

