---
layout: post
title: Comunismo sin partidos de masas
date: 2011-12-09 11:41:42.000000000 +01:00
type: recorte
categories:
- política
tags:
- "#VIAssembleaEUiA"
- comunismo
- euia
- Partido
---
<p><strong>Título</strong>: Dilemas del comunismo a caballo entre dos épocas<br />
<strong><strong>Autores</strong>: </strong>Joaquin Miras, Joan Tafalla<strong><br />
<strong>Publicación</strong>: </strong>El Viejo Topo, enero 2002<br />
<strong>Fuente: </strong><a href="http://www.profesionalespcm.org/docs/comunismo2epocas.html">http://www.profesionalespcm.org/docs/comunismo2epocas.html<br />
</a></p>
<p><em>PD</em>: lo que sigue es un extracto de un artículo que recomiendo leer entero</p>
<p><em>PPD</em>: añado la nueva etiqueta #VIAssembleaEUiA, etiqueta <em>twittera</em> propuesta por algunos compañeros para el proceso de elaboración y debate previo a la VI Assemblea d'EUiA (que tendrá lugar en primavera). Aunque escrito en 2002, los elementos que analiza me parecen de total actualidad.</p>
<hr size="1" noshade="noshade" />
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;"><strong>¿Sobrevivirá el comunismo a la desaparición de los partidos comunistas de masas?</strong></p>
<p>Lo hemos dicho al principio: los abajo firmantes apostamos y deseamos que así sea. Pero los deseos no siempre se cumplen. En este apartado final, trataremos de mostrar, brevemente, las condiciones sociales que harían plausible este deseo . Para ello quizá sea útil seguir el consejo marxiano de no "... sacar la poesía del pasado, sino solamente del porvenir..." y tratar de no empezar nuestra tarea "... antes de despojarnos de toda veneración supersticiosa por el pasado".</p>
<p>El proletariado postfordista, ¿cómo es? ¿En qué condiciones se desarrolla, se socializa, construye su identidad, si es que lo hace?. El espacio disponible nos permite sólo unas pinceladas.</p>
<p>La formas del trabajo han cambiado de forma radical y tienden a hacerlo cada vez más. Alguna de estas formas son más tecnificadas, exigen una fuerza de trabajo más culta que produce más plusvalía y a la que se explota de forma tanto o más acusada que en el pasado. Otras formas del trabajo exigen una fuerza de trabajo dispuesta a cualquier empleo, a cualquier horario, a cualquier forma de contrato. La universalidad de la escolarización hace que las nuevas generaciones se debatan entre el espejismo de ver bastantes hijos de trabajadores en la universidad y el fracaso escolar de amplísimas capas que lanza a partes importantes de la juventud al abismo de la rabia, de la marginación. En ambo casos, el paro y la precariedad serán el signo bajo el cual estos jóvenes harán su experiencia de socialización, y construirán su identidad.</p>
<p>El neoliberalismo deconstruye preventivamente la clase tras haberle roto la columna vertebral con las grandes reestucturaciones y desindustrialización de los años ochenta y noventa. La corrosión del carácter implícita en las nuevas formas de tele trabajo o en la movilidad permanente geográfica, funcional y contractual en el sector servicios, también conspiran contra la reconstitución del proletariado en clase.</p>
<p>Las grandes empresa fordistas desaparecen, reducen su tamaño y/o cambian de paradigma de la producción. La división internacional del trabajo facilita la dispersión de los diversos segmentos de la producción, la reducción de los costes del trabajo utilizando la competencia internacional entre los diversos segmentos nacionales de la clase obrera en el mercado de trabajo internacional.</p>
<p>En las grandes empresas industriales, la transición del fordismo al toyotismo se realiza de forma paralela a la liquidación de la generación obrera protagonista de las grandes luchas de los sesenta/setenta vía las reducciones de plantilla o los contratos-relevo. Tras esos procesos, quedan plantillas más reducidas, más jóvenes, con mayor formación escolar y técnica y menor memoria de clase, obligadas al trabajo cooperativo, a la toma de decisiones en equipo y a la asunción de responsabilidades por mor de las diversas formas del toyotismo. Las deslocalizaciones, las externalizaciones, las subcontratas, la temporalidad contractual y la multiplicación de los turnos de trabajo, vienen a complicar aún más la posibilidad de unificar a la clase. El traspaso de la memoria històrica de clase se transforma en prácticamente imposible El proceso de fragmentación de la clase a golpes de reforma laboral y gracias al crecimiento de la precariedad condiciona duramente el proceso. Asistimos al pase de la sociedad del pleno empleo a la sociedad precaria. Este modelo de sociedad busca la disponibilidad y la flexibilidad total de la fuerza de trabajo, la desregulación y la individualización totales de la relaciones laborales así como la desaparición de los sindicatos como portadores del conflicto social.</p>
<p>Por otra parte, las corrientes migratorias son utilizadas de forma consciente con la finalidad de hacer crecer el ejército industrial de reserva, de agudizar la competencia interna en la fuerza de trabajo disponible en cada estado, alimentando las contradiciones internas de la clase con un discurso racista. Si sumamos este fenómeno al del fracaso escolar al que hemos aludido más arriba, a la descomposición de la familia tradicional, cuyo papel educativo no puede ser suplido por una escuela sin medios, encontaremos bases para el crecimiento del racismo y del fascismo en nuestras conurbaciones Muchos trabajadores poseen una formación muy superior a la que sería requisito para su trabajo. Un segmento de trabajadores, gracias a las nuevas tecnologías han adquirido mayor control sobre la actividad que ejercen. Diversos tratadistas (Piore, Sabel, Revelli, Negri, Trentin, Coriat, etc. ) muestran que las nuevas tecnologías punta rompen con la lógica del control y de la subsunción real del trabajo al capital, y abren un nuevo frente a la lucha de clases. Son trabajadores cuyas tecnologías exigen de la permanente activación de la concepción y la ejecución, al estilo de los antiguos artesanos de mediados de los años cuarenta del siglo XIX que dieron nombre a su movimiento: comunismo.</p>
<p>Si es cierto que la diferenciación por segmentos se ha acrecentado con respecto a la homogeneidad del periodo fordista, en el que con todo existían diferencias que no se supieron comprender ni resolver adecuadamente, no es menos cierto, que tras la homogeneización civilizatoria generada por el capitalismo del consumo, en el periodo anterior, estas diferencias son muy relativas, y más si tenemos en cuenta las verdaderas diferencias que existían entre los diversos segmentos que, mediante la organización, y la deliberación política pública hicieron posible la constitución de la clase obrera (Making classe) en clase en el siglo XIX, como nos mostró Thompson.</p>
<p>Desde el 1 de enero de 1994, conocemos formas de resistencia y de rebelión a nivel mundial que auguran un futuro para el comunismo ( quizás no tanto para lo partidos herederos o restos del naufragio de los partidos comunistas). Chiapas, el MST, Corea del Sur, Indonesia, Francia en el 95, Italia... La movilización antiglobalización neoliberal con Seattle, Praga, Niza, Barcelona, Génova... la movilización antiguerra imperialista en Afganistán. Sin embargo, al menos en Europa, aún son patrimonio de una vanguardia amplia y, salvo en Francia, aún no afectan a las entrañas del sistema productivo, a la sala de máquinas del capitalismo, allí donde el sistema ejerce su hegemonía. Allí donde, en primer lugar, debe reconstituirse la subjetividad revolucionaria.</p>
<p>Las futuras formas de organización política del comunismo seran fruto del conjunto de individualidades que participen en el proceso constituyente de la nueva subjetividad revolucionaria. En definitiva, en la re-constitución del proletariado en clase para sí, para decir lo mismo con otro utillaje conceptual.</p>
<p>Cada individualidad, cada grupo social aportará su opinión fundamentada en su experiencia vital, que, por ello, es absolutamente verdadera. Esta reconstitución deberá basarse en la deliberación pública, en la libertad de palabra y de opinión, en el espíritu cooperativo, en la ausencia de autoritarismo... En fin, en la democracia como fundamento organizador de la futura clase obrera constituida en demos.</p>
<p>En resumen, los abajo firmantes creemos que si bien las condiciones son difíciles, existe base suficiente y amplia para la reconstitución de los trabajadores en clase, para quepueda prender una opción comunista en el siglo que hemos empezado.</p>
<p style="text-align: center;"><strong>Pero, ¿ y en el interín?</strong></p>
<p>Pero bueno, pensarán algunos lectores lo que empezó como una polémica sobre la conveniencia de presentar un cartel electoral u otro se ha tranformado en otra cosa. ¿Qué solución práctica nos proponen estos escribanos? Ciertamente no era otra la intención de los abajo firmantes: cambiar de tercio.</p>
<p>Entrar en lo práctico. Reconocer que no hay posibilidad de que ni IU, ni EuiA, ni el PCE, el PCC o el PSUC tengan espacio electoral sin que previamente se haya dado una periodo importante de reconstitución de subjetividad transformadora. Que las rentas electorales de las luchas de los sesenta/ setenta se han acabado o les queda sólo un ciclo lectoral para llegar a su fin. Que ser pragmático no es nada práctico. Dicho en otras palabras: que continuar debatiendo hasta la saciedad el cartel electoral no habiendo espacio socio- político no solo no sirve de nada: es el camino más corto haca la desaparición.</p>
<p>¿Que hacer en el interín? Volverá a inquirir el pragmático. Si la pregunta trata de encontrar una respuestra en el terreno de la fórmula electoral, confesamos inmediatamente nuestra incompetencia. No sabemos, en la actual situación qué cartel electoral sea el más útil. Como excusa para nuestra incompetencia quizá podamos aducir que no creemos que haya nadie que lo sepa. Mal de muchos... Quizá una prudencia elemental consista en no tocar nada, en preservar lo que hay (IU), en espera/preparación/ organización de un nuevo ciclo de luchas, de un despertar de la subjetividad. Ahora bien, mientras el espacio electoral se reduce progresivamente en el camino de la desaparición, ¿ qué se puede hacer para hacer para tender puentes entre el viejo comunismo del siglo XX y el neocomunismo que viene y vendrá en el presente siglo? Quizás cuatro o cinco cosas elementales: reconocer que el terreno privilegiado de la política no es el estado ni las instituciones si no la sociedad civil; invertir todos los esfuerzos en el desarrollo de sociedad civil alternativa, en movimientos sociales de constestación al sistema y no en los de integración en el mismo; hacer encuesta militante ( como en Italia) sobre la nueva composición de la clase obrera; conservar e innovar el patrimonio teórico; difundirlo entre las nuevas generaciones; renovar el concepto de democracia, de política, de estato y de revolución; practicar fuera (en los movimientos sociales y en las instituciones donde aún estamos) y en el interior de las organizaciones (IU. PCE, PSUC, PCC; sindicatos...) la democracia participativa , abandonando la prácticas de delegación que crean, indefectiblemente las burocracias con intereses corporativos, al margen, e incluso contra, el proyecto dela reconstitución la autonomia del sujeto. Y paciencia, mucha paciencia. Quien no la tenga tiene dos caminos : el de casa y el de la tercera via. Sencillo, simple... Si todo lo demás ya lo hemos practicado con los resultados que podemos apreciar, , ¿por qué no le damos una oportunidad al sentido común?</p>
